
add_newline = false

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](bold red)"

[line_break]
disabled = true

format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$package\
$python\
$env_var\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$shell\
$symbol """
